"""Added currency field in table person

Revision ID: 82f4833b2146
Revises: 5e4b6d1c0543
Create Date: 2025-02-06 22:16:04.894445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '82f4833b2146'
down_revision: Union[str, None] = '5e4b6d1c0543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'person',
        sa.Column(
            'currency',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'currency')
    # ### end Alembic commands ###
