name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
  workflow_dispatch:


jobs:
  lint:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.13"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Look for style errors
        run: uv run task lint

      - name: Look for formatting errors
        run: uvx ruff format --diff dundie tests integration

  # tests:
  #   needs: lint
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [ubuntu-latest]
  #       python-version: ["3.10", "3.11", "3.13"]
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-python@v4
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #
  #     - name: Install uv
  #       uses: astral-sh/setup-uv@v3
  #
  #     - name: Set up Python ${{ matrix.python-version }}
  #       run: uv python install ${{ matrix.python-version }}
  #
  #     - name: Install the project
  #       run: uv sync --all-extras --dev
  #
  #     - name: Run tests
  #       run: uv run --extra test pytest -v --cov=dundie --forked